#TODO: change website
#TODO: change docker command
# https://www.ansible.com/
# 
# docker run --rm \
#       -it \
#       -v ${PWD}/hosts:/etc/ansible/hosts \
#       -v ${PWD}/ansible.cfg:/etc/ansible/ansible.cfg \
#       -v ${HOME}/.ssh:/root/.ssh:ro \
#       ansible all -m ping
#
FROM alpine:latest
LABEL maintainer "Bill Brubaker <brubaker.bill+saltstackcontainer@gmail.com>"


